package org.javaboy.grpc.demo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source:  product.proto

public interface ProductIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:product.ProductId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string value = 1;</code>
   * @return The value.
   */
  String getValue();
  /**
   * <code>string value = 1;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
